/* Network Sync launch builder and simulation/receipt-verification helpers. Public beta v1.1.8 does not submit new transactions. */
(function(){
'use strict';
const CHAIN=4663,FACTORY='0x3ea29975a79900179F3e1aEF93347Ba4210c29C1',PRICER='0x9EfC6EFA4c5F31e2BEC6CC174Ba7bB8f0b57d563',VAULT='0x4B79B8298cd890A82dC9De1dE5dBb745Cf04353C',SYNC='0x6368e007b9f0b941560ed1f3bceb20247f5eca37';
const ZERO='0x'+'00'.repeat(32),address=/^0x[a-fA-F0-9]{40}$/,hash=/^0x[a-fA-F0-9]{64}$/;
const equal=(a,b)=>String(a).toLowerCase()===String(b).toLowerCase();
const components=[{name:'name',type:'string'},{name:'symbol',type:'string'},{name:'logo',type:'string'},{name:'description',type:'string'},{name:'socials',type:'tuple',components:['twitter','telegram','discord','website','farcaster'].map(name=>({name,type:'string'}))},{name:'creatorFeeRecipient',type:'address'},{name:'creatorTaxBps',type:'uint16'},{name:'expectedEconomics',type:'bytes32'},{name:'salt',type:'bytes32'}];
const ABI=[{type:'function',name:'launchToken',stateMutability:'payable',inputs:[{name:'params',type:'tuple',components},{name:'launchConfigId',type:'uint256'},{name:'pairTokens',type:'address[]'}],outputs:[{name:'token',type:'address'}]},
{type:'event',name:'TokenLaunched',inputs:[{name:'token',type:'address',indexed:true},{name:'deployer',type:'address',indexed:true},{name:'launchConfigId',type:'uint256',indexed:false},{name:'poolFee',type:'uint24',indexed:false},{name:'pairTokens',type:'address[]',indexed:false}]},
{type:'event',name:'MarketOpened',inputs:[{name:'token',type:'address',indexed:true},{name:'poolId',type:'bytes32',indexed:true},...['marketIndex:uint256','pairToken:address','positionId:uint256','tickLower:int24','tickUpper:int24','liquidity:uint128','tokenAmount:uint256','phantomQuote:uint256'].map(s=>{const[name,type]=s.split(':');return {name,type,indexed:false}})]}];
function read(client,to,name,args=[],types=[],output='uint256'){return client.readContract({address:to,abi:[{type:'function',name,stateMutability:'view',inputs:types.map(type=>({type})),outputs:[{type:output}]}],functionName:name,args})}
async function walletState(provider,account){if(Number(await provider.request({method:'eth_chainId'}))!==CHAIN)throw Error('Switch your wallet to Robinhood Chain.');const accounts=await provider.request({method:'eth_accounts'});if(!accounts?.[0]||!equal(accounts[0],account))throw Error('Wallet account changed. Prepare the launch again.');}
function logo(value){value=String(value||'').trim();if(!value)return '';if(value.length>2048)throw Error('Logo URL is too long.');if(/^ipfs:\/\/[a-zA-Z0-9]+(?:\/[a-zA-Z0-9._~/-]+)?$/.test(value))return value;try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password&&!/[\u0000-\u0020]/.test(value))return u.href}catch{}throw Error('Use a public HTTPS or IPFS logo URL. Local preview images cannot be stored as the token logo.');}
function normalize(draft){if(draft.mode!=='network')throw Error('Stable Sync launch is not available. Select Network Sync.');if(!address.test(draft.account)||!address.test(draft.external)||equal(draft.external,SYNC)||/^0x0{40}$/i.test(draft.external))throw Error('Choose a valid external token different from SYNC.');const name=String(draft.name||'').trim(),symbol=String(draft.symbol||'').trim().toUpperCase();if(!name||name.length>40||!/^[A-Z0-9]{1,10}$/.test(symbol))throw Error('Enter a name (up to 40 characters) and a ticker (1–10 letters or numbers).');if(![0,100,250,500,1000].includes(draft.tax))throw Error('Invalid creator tax.');const description=String(draft.description||'').trim();if(description.length>1000)throw Error('Description must be at most 1,000 characters.');for(const value of [draft.twitter,draft.website])if(value){const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Invalid social URL.');}return {...draft,name,symbol,description,logo:logo(draft.logo)};}
async function eligibility(client,draft){if(await client.getChainId()!==CHAIN)throw Error('RPC returned an unexpected chain.');const [can,ext,sync,fee,base,max]=await Promise.all([read(client,FACTORY,'canLaunch',[draft.account],['address'],'bool'),read(client,PRICER,'isPriceable',[draft.external],['address'],'bool'),read(client,PRICER,'isPriceable',[SYNC],['address'],'bool'),read(client,FACTORY,'launchFee'),read(client,FACTORY,'baseFeeBps'),read(client,FACTORY,'maxCreatorTaxBps')]);if(!can)throw Error('PAR currently does not allow this wallet to launch.');if(!ext||!sync)throw Error((!ext?'The selected asset':'SYNC')+' is not currently eligible. No transaction was requested.');if(BigInt(draft.tax)>max)throw Error('Creator tax exceeds the current PAR limit.');return {fee,base,poolFee:Number((base+BigInt(draft.tax))*100n)};}
async function prepare({client,provider,draft,viem,assertCurrent=()=>{}}){draft=normalize(draft);delete draft.artwork;await walletState(provider,draft.account);assertCurrent();const terms=await eligibility(client,draft);assertCurrent();for(const to of [FACTORY,VAULT,draft.external,SYNC]){const code=await client.getBytecode({address:to});if(!code||code==='0x')throw Error('A required contract is missing on this network.');assertCurrent();}const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const salt='0x'+Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
const params={name:draft.name,symbol:draft.symbol,logo:draft.logo,description:draft.description,socials:{twitter:draft.twitter||'',telegram:'',discord:'',website:draft.website||'',farcaster:''},creatorFeeRecipient:VAULT,creatorTaxBps:draft.tax,expectedEconomics:ZERO,salt};
const data=viem.encodeFunctionData({abi:ABI,functionName:'launchToken',args:[params,0n,[draft.external,SYNC]]});const request={account:draft.account,to:FACTORY,data,value:terms.fee};const result=await client.call(request);assertCurrent();const predicted=viem.decodeFunctionResult({abi:ABI,functionName:'launchToken',data:result.data});if(!address.test(predicted)||/^0x0{40}$/i.test(predicted))throw Error('Simulation returned an invalid token address.');const gas=await client.estimateGas(request);assertCurrent();await walletState(provider,draft.account);assertCurrent();return {schemaVersion:1,draft,params,predicted,createdAt:Date.now(),poolFee:terms.poolFee,baseFeeBps:Number(terms.base),request:{from:draft.account,to:FACTORY,data,value:viem.toHex(terms.fee),gas:viem.toHex((gas*150n+99n)/100n),chainId:'0x1237'}};}
async function recheck({client,provider,prepared,assertCurrent=()=>{}}){if(Date.now()-prepared.createdAt>90000)throw Error('This launch preview expired. Prepare it again.');assertCurrent();await walletState(provider,prepared.draft.account);assertCurrent();const terms=await eligibility(client,prepared.draft);assertCurrent();if(terms.fee!==BigInt(prepared.request.value)||terms.poolFee!==prepared.poolFee)throw Error('PAR fees changed. Prepare the launch again and review the updated amounts.');await client.call({account:prepared.request.from,to:FACTORY,data:prepared.request.data,value:terms.fee,gas:BigInt(prepared.request.gas)});assertCurrent();await walletState(provider,prepared.draft.account);assertCurrent();}
async function verify({client,viem,prepared,transactionHash,receipt}){if(!hash.test(transactionHash))throw Error('Invalid transaction hash.');if(await client.getChainId()!==CHAIN)throw Error('Unexpected receipt network.');receipt=receipt||await client.getTransactionReceipt({hash:transactionHash});if(!equal(receipt.transactionHash,transactionHash)||!equal(receipt.to,FACTORY)||!equal(receipt.from,prepared.request.from))throw Error('Receipt does not match the launch factory and wallet.');const tx=await client.getTransaction({hash:transactionHash});if(!equal(tx.to,FACTORY)||!equal(tx.from,prepared.request.from)||!equal(tx.input,prepared.request.data)||tx.value!==BigInt(prepared.request.value)||!equal(tx.blockHash,receipt.blockHash))throw Error('The mined transaction differs from the reviewed launch.');if(receipt.status!=='success')throw Object.assign(Error('Launch transaction reverted. No token was created by this transaction.'),{reverted:true});const block=await client.getBlock({blockNumber:receipt.blockNumber});if(!equal(block.hash,receipt.blockHash))throw Error('Receipt block changed. Check transaction status again.');const events=[];for(const log of receipt.logs){if(!equal(log.address,FACTORY))continue;try{events.push(viem.decodeEventLog({abi:ABI,data:log.data,topics:log.topics,strict:true}))}catch{}}
const launches=events.filter(x=>x.eventName==='TokenLaunched');if(launches.length!==1)throw Error('Expected one matching factory launch event.');const a=launches[0].args;if(!equal(a.token,prepared.predicted)||!equal(a.deployer,prepared.request.from)||a.launchConfigId!==0n||Number(a.poolFee)!==prepared.poolFee||a.pairTokens.length!==2||!equal(a.pairTokens[0],prepared.draft.external)||!equal(a.pairTokens[1],SYNC))throw Error('Launch event differs from the reviewed token or markets.');const markets=events.filter(x=>x.eventName==='MarketOpened');if(markets.length!==2)throw Error('Expected two market creation events.');for(let i=0;i<2;i++){const m=markets.find(x=>Number(x.args.marketIndex)===i)?.args;if(!m||!equal(m.token,a.token)||!equal(m.pairToken,a.pairTokens[i])||m.liquidity<=0n||m.tokenAmount<=0n)throw Error('A market event is missing or does not match.');}const code=await client.getBytecode({address:a.token});if(!code||code==='0x')throw Error('Launched token code is not yet available. Retry confirmation.');return {token:a.token,transactionHash,blockNumber:receipt.blockNumber.toString(),blockHash:receipt.blockHash,chainId:CHAIN,name:prepared.draft.name,symbol:prepared.draft.symbol,markets:[prepared.draft.external,SYNC],creatorTaxBps:prepared.draft.tax,creatorFeeRecipient:VAULT,scope:'on-chain receipt verified in this browser; not a SyncNet registry admission'};}
window.SyncNetLaunch=Object.freeze({prepare,recheck,verify,normalize,logo,ABI,FACTORY,VAULT,SYNC});
})();
