// Quick end-to-end smoke of the founder launch path (development aid; the full suites are run.mjs and tests/regression).
import { startServer, installRoutes, A, chain, resetChain, resetServer, FOUNDER_KEY, serverState, TEST_CID } from './harness.mjs';
const { chromium } = await import('playwright').catch(() => import(process.env.PLAYWRIGHT_MODULE || '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs'));
const BASE = 'http://localhost:8932';
const srv = await startServer(8932);
const browser = await chromium.launch();
resetChain(); resetServer();
const c = await browser.newContext({ viewport: { width: 1280, height: 900 } }); await installRoutes(c);
const page = await c.newPage(); const errs = [];
page.on('pageerror', (e) => errs.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
page.on('dialog', (d) => d.accept());
const t0 = Date.now(); const log = (...a) => console.log(((Date.now() - t0) / 1000).toFixed(1) + 's', ...a);
await page.goto(BASE + '/build.html?live=canary');
log('banner:', await page.textContent('#networkBanner'));
await page.click('#tab-4'); await page.fill('#canaryKey', FOUNDER_KEY); await page.click('#unlockCanary');
await page.waitForSelector('#liveCanary:not([hidden])', { timeout: 8000 });
log('unlocked; banner:', await page.textContent('#networkBanner'));
await page.click('#tab-1'); await page.click('#panel-1 summary'); await page.fill('#logo', 'ipfs://' + TEST_CID);
await page.fill('#name', 'Smoke Test'); await page.fill('#symbol', 'SMOKE'); await page.fill('#description', 'A smoke test project');
await page.check('input[name="websiteChoice"][value="none"]');
await page.click('#tab-2'); await page.click('[data-preset="SYNC"]'); await page.waitForFunction(() => /SYNC ready/.test(document.getElementById('assetStatus').textContent));
await page.click('#tab-3'); await page.click('[data-tax="100"]'); await page.check('input[name="feeMode"][value="creator"]');
await page.click('#tab-4'); await page.click('#connectWallet'); await page.click('#providerList button');
await page.click('#runSimulation');
await page.waitForFunction(() => /SIMULATION PASSED|No transaction was sent/.test(document.getElementById('simStatus').textContent), null, { timeout: 30000 });
log('sim:', (await page.textContent('#simStatus')).slice(0, 300));
await page.waitForFunction(() => /PASS|BLOCKED|EXISTS|WARN/.test(document.getElementById('checkDuplicate').textContent), null, { timeout: 15000 });
log('dup:', await page.textContent('#checkDuplicate'), '| guard:', (await page.textContent('#guardPanel')).slice(0, 200));
await page.click('#signIntent'); await page.waitForFunction(() => /SIGNED|NOT SIGNED/.test(document.getElementById('checkIntentSignature').textContent) && !/SIGNING/.test(document.getElementById('checkIntentSignature').textContent));
log('sig:', await page.textContent('#checkIntentSignature'));
log('final review visible:', await page.locator('#finalReview').isVisible());
log('blockers:', await page.textContent('#launchBlockers'));
await page.check('#finalAck');
await page.fill('#liveConfirm', 'SMOKE');
log('blockers after ack:', await page.textContent('#launchBlockers'), '| launch enabled:', await page.locator('#launchLive').isEnabled());
await page.click('#launchLive');
await page.waitForFunction(() => /LIVE LAUNCH CONFIRMED|VERIFICATION NEEDS|Nothing was sent|treated as SENT|REVERTED/.test(document.getElementById('liveStatus').textContent), null, { timeout: 60000 });
log('live:', (await page.textContent('#liveStatus')).slice(0, 900));
log('records:', await page.evaluate(() => JSON.parse(localStorage.getItem('syncnet_launch_records_v1') || '[]').map((r) => r.state + ' ' + r.predicted + ' ' + (r.txHash || '')).join(' | ')));
log('registry pins/logs:', serverState.pins.length, serverState.logs.filter((l) => l.fn).map((l) => l.fn + ':' + l.event).join(','));
log('errors:', errs.join(' | ') || 'none');
await browser.close(); srv.close();
